version: '3.3'

services:
  mongo:
    image: mongo:3
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: 10.5.0.3

networks:
  vpcbr:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/29
#          gateway: 10.5.0.1